version: "3"
services:
  postgresDb:
    image: "postgres"
    restart: always
    container_name: "postgres_container"
    #   Setup the username, password, and database name. You can changes these values.
    environment:
      - POSTGRES_USER=jimseconde
      - POSTGRES_PASSWORD=jimseconde
      - POSTGRES_DB=hoopy
    ports:
      - "54320:5432"
  redisDb:
    image: "redis"
    restart: always
    container_name: "redis_container"