version: "3"
services:
  postgresDb:
    image: "postgres:latest"
    restart: always
    container_name: "postgres_container"
    #   Setup the username, password, and database name. You can changes these values.
    environment:
      - POSTGRES_USER=jimseconde
      - POSTGRES_PASSWORD=jimseconde
      - POSTGRES_DB=hoopy